name: Code Quality

on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres

    # Docs: https://docs.github.com/en/actions/using-containerized-services
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo pdo_pgsql pgsql bcmath
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm i --frozen-lockfile

      - name: Build JS
        run: npm run build

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Clear Config
        run: php artisan config:clear

      - name: Run Migration
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Test with pest
        run: php artisan test --coverage-text
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Pint!
        run: vendor/bin/pint --test
      
      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update Installation Data
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        run: |
          php artisan ide-helper:actions
          vendor/bin/pint _ide_helper_actions.php
          php artisan migrate:fresh
          php artisan app:self-host-ptah > scripts/self-hosted/tasks.json
          npx prettier --write scripts/self-hosted/tasks.json
          
          cat << EOF > scripts/self-hosted/db.sql
          BEGIN WORK ISOLATION LEVEL SERIALIZABLE;
          EOF
          
          docker run --rm \
            --network="host" \
            --env PGPASSWORD=$DB_PASSWORD \
            postgres \
            pg_dump \
            -U $DB_USERNAME \
            -h localhost \
            -d $DB_DATABASE \
            -p $DB_PORT \
            --clean --if-exists \
            --no-owner --no-acl \
            >> scripts/self-hosted/db.sql

          cat << EOF >> scripts/self-hosted/db.sql
          COMMIT;
          EOF

          scripts/self-hosted/make-installers.sh

          # Check if there are any changes to commit
          if git diff --exit-code && git diff --staged --exit-code; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "chore: update installation data" -n
            git push
          fi
